stages:
  - mirror
  - deploy

mirror_danh_to_github_main:
  stage: mirror
  image: alpine/git:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "danh"'
  script:
    - '[ -z "$GITHUB_TOKEN" ] && { echo "ERROR: GITHUB_TOKEN is empty in GitLab Variables!"; exit 1; }'
    - '[ -z "$GITHUB_MIRROR_REPO" ] && { echo "ERROR: GITHUB_MIRROR_REPO is empty in GitLab Variables!"; exit 1; }'
    - git remote add github "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_MIRROR_REPO}.git"
    - git push --force github "HEAD:refs/heads/main"

deploy_production:
  stage: deploy
  image: node:20-alpine
  only:
    - cuong #sửa tên nhánh ở đây, muốn push lên nhánh dev mới deploy thì sửa thành "dev"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - node_modules/
      - .next/cache/
  script:
    - npm config set cache .npm/
    - npm install -g vercel
    - "[ -z \"$VERCEL_TOKEN\" ] && { echo \"ERROR: VERCEL_TOKEN is empty in GitLab Variables!\"; exit 1; }"
    - "[ -z \"$VERCEL_ORG_ID\" ] && { echo \"ERROR: VERCEL_ORG_ID is empty in GitLab Variables!\"; exit 1; }"
    - "[ -z \"$VERCEL_PROJECT_ID\" ] && { echo \"ERROR: VERCEL_PROJECT_ID is empty in GitLab Variables!\"; exit 1; }"
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
